spring.application.name=tigo-backend
spring.datasource.url=${NEON_JDBC_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${NEON_DB_USERNAME}
spring.datasource.password=${NEON_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://ep-small-dew-asbun3wu.neonauth.c-4.eu-central-1.aws.neon.tech/neondb/auth/.well-known/jwks.json
server.port=8081